name: Check Code Formatting 🛠️
on:
  workflow_call:
jobs:
  cmake-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cmake-format check 🎛️
        id: cmake-format
        uses: ./.github/actions/run-cmake-format
        with:
          failCondition: error
